
codecov:
  token: c47dd13b-aa4e-4505-bd8f-8237343afb18

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
